worker_name: "RoFo Horde Worker#1"
nsfw: true

# This notebook will always attempt to load
# one model with a low worker count and one
# with a long queue time in addition to
# the models defined here

# Controlnet, painting and postprocessing 
# will be determined according to instance spec
always_load:
    - "Deliberate"
    - "Waifu Diffusion"
    
never_load:
    - "ALL_NSFW"