dreamer_name: "An Awesome Dreamer"
nsfw: true
censor_nsfw: false
blacklist: []
censorlist: []
allow_unsafe_ip: true
stats_output_frequency: 30
cache_home: "./"
always_download: true
temp_dir: "./tmp"
disable_terminal_ui: true
disable_disk_cache: false