### Dreamer ###

# 3@20, 2@24
max_threads: 2
queue_size: 0
max_power: 24
allow_img2img: true
allow_painting: true
allow_post_processing: true
allow_controlnet: false
vram_to_leave_free: "20%"
ram_to_leave_free: "20%"
dynamic_models: false
number_of_dynamic_models: 0
max_models_to_download: 10
models_to_load:
  - "TOP 4"
  #- "stable_diffusion_inpainting"
models_to_skip:
  - "pix2pix"

### Scribe ###

max_length: 80
max_context_length: 1024

### Alchemist ###

forms:
  - "caption"
  - "nsfw" # uses CPU
  # Heavier than the others, but rewards more kudos
  #- "interrogation"
  #- "post-process"
